package Utils;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

public class PDFGeneratorUtil {

    // Main generation method
    public static void generateReport(OutputStream out, String reportTitle, String username, 
                                      String headerText, String footerText, 
                                      String[] columnHeaders, List<String[]> rowData) throws DocumentException {
        
        // 1. Enforce Landscape Orientation (SRS Rule)
        Document document = new Document(PageSize.A4.rotate());
        PdfWriter writer = PdfWriter.getInstance(document, out);
        
        // 2. Attach the custom event for Headers, Footers, and Pagination
        HeaderFooterPageEvent event = new HeaderFooterPageEvent(headerText, footerText, username);
        writer.setPageEvent(event);
        
        document.open();

        // 3. Add Report Title and Timestamp
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, BaseColor.DARK_GRAY);
        Paragraph title = new Paragraph(reportTitle, titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(10f);
        document.add(title);

        Font metaFont = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.GRAY);
        String timestamp = new SimpleDateFormat("MMMM dd, yyyy - hh:mm a").format(new Date());
        Paragraph meta = new Paragraph("Generated by: " + username + " | Date: " + timestamp, metaFont);
        meta.setAlignment(Element.ALIGN_CENTER);
        meta.setSpacingAfter(20f);
        document.add(meta);

        // 4. Build the Data Table
        PdfPTable table = new PdfPTable(columnHeaders.length);
        table.setWidthPercentage(100);

        // Add Headers
        Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, BaseColor.WHITE);
        for (String header : columnHeaders) {
            PdfPCell cell = new PdfPCell(new Phrase(header, headerFont));
            cell.setBackgroundColor(new BaseColor(30, 58, 95)); // Matches your CSS --primary
            cell.setPadding(8f);
            table.addCell(cell);
        }

        // Add Data Rows
        Font rowFont = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.BLACK);
        for (String[] row : rowData) {
            for (String cellData : row) {
                PdfPCell cell = new PdfPCell(new Phrase(cellData != null ? cellData : "", rowFont));
                cell.setPadding(6f);
                table.addCell(cell);
            }
        }

        if (rowData.isEmpty()) {
            PdfPCell emptyCell = new PdfPCell(new Phrase("No records found.", rowFont));
            emptyCell.setColspan(columnHeaders.length);
            emptyCell.setHorizontalAlignment(Element.ALIGN_CENTER);
            emptyCell.setPadding(15f);
            table.addCell(emptyCell);
        }

        document.add(table);
        document.close();
    }

    // Inner class to handle Page x of y, Headers, and Footers
    static class HeaderFooterPageEvent extends PdfPageEventHelper {
        private String headerText;
        private String footerText;
        private String username;
        private PdfTemplate totalPagesTemplate;
        private Font baseFont = FontFactory.getFont(FontFactory.HELVETICA, 9, BaseColor.GRAY);

        public HeaderFooterPageEvent(String headerText, String footerText, String username) {
            this.headerText = headerText;
            this.footerText = footerText;
            this.username = username;
        }

        @Override
        public void onOpenDocument(PdfWriter writer, Document document) {
            totalPagesTemplate = writer.getDirectContent().createTemplate(30, 12);
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            PdfContentByte cb = writer.getDirectContent();
            
            // Header
            ColumnText.showTextAligned(cb, Element.ALIGN_RIGHT, new Phrase(headerText, baseFont), 
                document.right(), document.top() + 10, 0);

            // Footer (Confidentiality text)
            ColumnText.showTextAligned(cb, Element.ALIGN_LEFT, new Phrase(footerText, baseFont), 
                document.left(), document.bottom() - 10, 0);

            // Pagination (Page x of y)
            String pageText = "Page " + writer.getPageNumber() + " of ";
            float textBase = document.bottom() - 10;
            float textSize = baseFont.getBaseFont().getWidthPoint(pageText, 9);
            
            cb.beginText();
            cb.setFontAndSize(baseFont.getBaseFont(), 9);
            cb.setTextMatrix(document.right() - textSize - 15, textBase);
            cb.showText(pageText);
            cb.endText();
            cb.addTemplate(totalPagesTemplate, document.right() - 15, textBase);
        }

        @Override
        public void onCloseDocument(PdfWriter writer, Document document) {
            ColumnText.showTextAligned(totalPagesTemplate, Element.ALIGN_LEFT, 
                new Phrase(String.valueOf(writer.getPageNumber()), baseFont), 2, 0, 0);
        }
    }
}